# Generated by Django 3.1.4 on 2021-01-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=5)),
                ('visits', models.CharField(max_length=5)),
                ('days', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SellSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.customers')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.subscriptions')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
         migrations.CreateModel(
             name='Staff',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('fio', models.CharField(max_length=250)),
                 ('address', models.CharField(max_length=150)),
                 ('birthday', models.DateField()),
                 ('salary', models.CharField(max_length=5)),
             ],
         ),
         migrations.CreateModel(
             name='Services',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('service_name', models.CharField(max_length=150)),
             ],
         ),
         migrations.CreateModel(
             name='KindSport',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.staff')),
                 ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.services')),
                 ('note', models.CharField(max_length=500, default='...')),
             ],
         ),
         migrations.CreateModel(
             name='Rooms',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('room_name', models.CharField(max_length=150)),
             ],
         ),
         migrations.CreateModel(
             name='Timetable',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('timetable_date', models.DateField()),
                 ('start_time', models.TimeField()),
                 ('end_time', models.TimeField()),
                 ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.services')),
                 ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.rooms')),
                 ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.kindsport')),
                 ('note', models.CharField(max_length=500, default='...')),
             ],
         ),
         migrations.CreateModel(
             name='RegistrationVisits',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('sellSubscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.sellsubscriptions')),
                 ('timetable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.timetable')),
             ],
         ),
    ]
