# Generated by Django 3.1.4 on 2021-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='position',
            field=models.IntegerField(choices=[(1, 'Position1'), (2, 'Position2'), (3, 'Position3')], max_length=150),
        ),
    ]
