# Generated by Django 3.1.4 on 2021-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210105_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='position',
            field=models.IntegerField(choices=[(1, 'Position1'), (2, 'Position2'), (3, 'Position3')]),
        ),
    ]
